# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Experimental Design and Data Analysis
description:      'Using the computer tools of a modern biologist'
url:              http://BIOL360.github.io/summer2018
baseurl:          /summer2018
email:            CliftonFranklund@ferris.edu
feedbackurl:      polleverywhere.com/multiple_choice_polls/KznOEBvSAnahmt7
author:
  name:           'Dr. Clifton Franklund'
  url:            https://twitter.com/Dr_Franklund

github:
  repo:           https://github.com/BIOL360/semester-biology
  #               Be sure the 'Issues' feature is activated in 'Settings'
